name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'typings/**'
      - 'template/**'
      - 'package.json'
      - 'yarn.lock'
    branches:
      - '*'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_BRANCH: ${{ github.ref }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          persist-credentials: false

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Release
        run: |
          npx semantic-release --no-ci --debug --dry-run
